/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CambiarContrasenaRouteImport } from './routes/cambiar-contrasena'
import { Route as ClinicaSuspendidaRouteImport } from './routes/clinica-suspendida'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MasterRouteImport } from './routes/master'
import { Route as OlvideContrasenaRouteImport } from './routes/olvide-contrasena'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AppAgendaRouteImport } from './routes/app/Agenda'
import { Route as AppConfiguracionRouteImport } from './routes/app/Configuracion'
import { Route as AppCrecimientoIARouteImport } from './routes/app/CrecimientoIA'
import { Route as AppDashboardRouteImport } from './routes/app/Dashboard'
import { Route as AppEquipoRouteImport } from './routes/app/Equipo'
import { Route as AppFinancieroRouteImport } from './routes/app/Financiero'
import { Route as AppInformesRouteImport } from './routes/app/Informes'
import { Route as AppOnboardingRouteImport } from './routes/app/Onboarding'
import { Route as AppPacientesRouteImport } from './routes/app/Pacientes'
import { Route as AppPresupuestosRouteImport } from './routes/app/Presupuestos'
import { Route as AppProcedimientosRouteImport } from './routes/app/Procedimientos'
import { Route as AppProfesionalesRouteImport } from './routes/app/Profesionales'
import { Route as AppTratamientosRouteImport } from './routes/app/Tratamientos'
import { Route as DemoAgendaRouteImport } from './routes/demo/Agenda'
import { Route as DemoCrecimientoIARouteImport } from './routes/demo/CrecimientoIA'
import { Route as DemoDashboardRouteImport } from './routes/demo/Dashboard'
import { Route as DemoFinancieroRouteImport } from './routes/demo/Financiero'
import { Route as DemoInformesRouteImport } from './routes/demo/Informes'
import { Route as DemoPacientesRouteImport } from './routes/demo/Pacientes'
import { Route as DemoPresupuestosRouteImport } from './routes/demo/Presupuestos'
import { Route as DemoTratamientosRouteImport } from './routes/demo/Tratamientos'
import { Route as MasterClinicasSuspendidasRouteImport } from './routes/master/clinicasSuspendidas'
import { Route as MasterConfiguracionRouteImport } from './routes/master/configuracion'
import { Route as MasterListaClinicasRouteImport } from './routes/master/listaClinicas'
import { Route as MasterNuevaClinicaRouteImport } from './routes/master/nuevaClinica'
import { Route as MasterPanelRouteImport } from './routes/master/panel'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarContrasenaRoute = CambiarContrasenaRouteImport.update({
  id: '/cambiar-contrasena',
  path: '/cambiar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaSuspendidaRoute = ClinicaSuspendidaRouteImport.update({
  id: '/clinica-suspendida',
  path: '/clinica-suspendida',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const OlvideContrasenaRoute = OlvideContrasenaRouteImport.update({
  id: '/olvide-contrasena',
  path: '/olvide-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/Agenda',
  path: '/Agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/Configuracion',
  path: '/Configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCrecimientoIARoute = AppCrecimientoIARouteImport.update({
  id: '/CrecimientoIA',
  path: '/CrecimientoIA',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipoRoute = AppEquipoRouteImport.update({
  id: '/Equipo',
  path: '/Equipo',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancieroRoute = AppFinancieroRouteImport.update({
  id: '/Financiero',
  path: '/Financiero',
  getParentRoute: () => AppRoute,
} as any)
const AppInformesRoute = AppInformesRouteImport.update({
  id: '/Informes',
  path: '/Informes',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/Onboarding',
  path: '/Onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/Pacientes',
  path: '/Pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppPresupuestosRoute = AppPresupuestosRouteImport.update({
  id: '/Presupuestos',
  path: '/Presupuestos',
  getParentRoute: () => AppRoute,
} as any)
const AppProcedimientosRoute = AppProcedimientosRouteImport.update({
  id: '/Procedimientos',
  path: '/Procedimientos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfesionalesRoute = AppProfesionalesRouteImport.update({
  id: '/Profesionales',
  path: '/Profesionales',
  getParentRoute: () => AppRoute,
} as any)
const AppTratamientosRoute = AppTratamientosRouteImport.update({
  id: '/Tratamientos',
  path: '/Tratamientos',
  getParentRoute: () => AppRoute,
} as any)
const DemoAgendaRoute = DemoAgendaRouteImport.update({
  id: '/Agenda',
  path: '/Agenda',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCrecimientoIARoute = DemoCrecimientoIARouteImport.update({
  id: '/CrecimientoIA',
  path: '/CrecimientoIA',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinancieroRoute = DemoFinancieroRouteImport.update({
  id: '/Financiero',
  path: '/Financiero',
  getParentRoute: () => DemoRoute,
} as any)
const DemoInformesRoute = DemoInformesRouteImport.update({
  id: '/Informes',
  path: '/Informes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPacientesRoute = DemoPacientesRouteImport.update({
  id: '/Pacientes',
  path: '/Pacientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPresupuestosRoute = DemoPresupuestosRouteImport.update({
  id: '/Presupuestos',
  path: '/Presupuestos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoTratamientosRoute = DemoTratamientosRouteImport.update({
  id: '/Tratamientos',
  path: '/Tratamientos',
  getParentRoute: () => DemoRoute,
} as any)
const MasterClinicasSuspendidasRoute =
  MasterClinicasSuspendidasRouteImport.update({
    id: '/clinicasSuspendidas',
    path: '/clinicasSuspendidas',
    getParentRoute: () => MasterRoute,
  } as any)
const MasterConfiguracionRoute = MasterConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => MasterRoute,
} as any)
const MasterListaClinicasRoute = MasterListaClinicasRouteImport.update({
  id: '/listaClinicas',
  path: '/listaClinicas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNuevaClinicaRoute = MasterNuevaClinicaRouteImport.update({
  id: '/nuevaClinica',
  path: '/nuevaClinica',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPanelRoute = MasterPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => MasterRoute,
} as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart-webhook',
  path: '/api/public/hotmart-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/clinica-suspendida': typeof ClinicaSuspendidaRoute
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/master': typeof MasterRouteWithChildren
  '/olvide-contrasena': typeof OlvideContrasenaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/Agenda': typeof AppAgendaRoute
  '/app/Configuracion': typeof AppConfiguracionRoute
  '/app/CrecimientoIA': typeof AppCrecimientoIARoute
  '/app/Dashboard': typeof AppDashboardRoute
  '/app/Equipo': typeof AppEquipoRoute
  '/app/Financiero': typeof AppFinancieroRoute
  '/app/Informes': typeof AppInformesRoute
  '/app/Onboarding': typeof AppOnboardingRoute
  '/app/Pacientes': typeof AppPacientesRoute
  '/app/Presupuestos': typeof AppPresupuestosRoute
  '/app/Procedimientos': typeof AppProcedimientosRoute
  '/app/Profesionales': typeof AppProfesionalesRoute
  '/app/Tratamientos': typeof AppTratamientosRoute
  '/demo/Agenda': typeof DemoAgendaRoute
  '/demo/CrecimientoIA': typeof DemoCrecimientoIARoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Financiero': typeof DemoFinancieroRoute
  '/demo/Informes': typeof DemoInformesRoute
  '/demo/Pacientes': typeof DemoPacientesRoute
  '/demo/Presupuestos': typeof DemoPresupuestosRoute
  '/demo/Tratamientos': typeof DemoTratamientosRoute
  '/master/clinicasSuspendidas': typeof MasterClinicasSuspendidasRoute
  '/master/configuracion': typeof MasterConfiguracionRoute
  '/master/listaClinicas': typeof MasterListaClinicasRoute
  '/master/nuevaClinica': typeof MasterNuevaClinicaRoute
  '/master/panel': typeof MasterPanelRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/clinica-suspendida': typeof ClinicaSuspendidaRoute
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/master': typeof MasterRouteWithChildren
  '/olvide-contrasena': typeof OlvideContrasenaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/Agenda': typeof AppAgendaRoute
  '/app/Configuracion': typeof AppConfiguracionRoute
  '/app/CrecimientoIA': typeof AppCrecimientoIARoute
  '/app/Dashboard': typeof AppDashboardRoute
  '/app/Equipo': typeof AppEquipoRoute
  '/app/Financiero': typeof AppFinancieroRoute
  '/app/Informes': typeof AppInformesRoute
  '/app/Onboarding': typeof AppOnboardingRoute
  '/app/Pacientes': typeof AppPacientesRoute
  '/app/Presupuestos': typeof AppPresupuestosRoute
  '/app/Procedimientos': typeof AppProcedimientosRoute
  '/app/Profesionales': typeof AppProfesionalesRoute
  '/app/Tratamientos': typeof AppTratamientosRoute
  '/demo/Agenda': typeof DemoAgendaRoute
  '/demo/CrecimientoIA': typeof DemoCrecimientoIARoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Financiero': typeof DemoFinancieroRoute
  '/demo/Informes': typeof DemoInformesRoute
  '/demo/Pacientes': typeof DemoPacientesRoute
  '/demo/Presupuestos': typeof DemoPresupuestosRoute
  '/demo/Tratamientos': typeof DemoTratamientosRoute
  '/master/clinicasSuspendidas': typeof MasterClinicasSuspendidasRoute
  '/master/configuracion': typeof MasterConfiguracionRoute
  '/master/listaClinicas': typeof MasterListaClinicasRoute
  '/master/nuevaClinica': typeof MasterNuevaClinicaRoute
  '/master/panel': typeof MasterPanelRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/clinica-suspendida': typeof ClinicaSuspendidaRoute
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/master': typeof MasterRouteWithChildren
  '/olvide-contrasena': typeof OlvideContrasenaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/Agenda': typeof AppAgendaRoute
  '/app/Configuracion': typeof AppConfiguracionRoute
  '/app/CrecimientoIA': typeof AppCrecimientoIARoute
  '/app/Dashboard': typeof AppDashboardRoute
  '/app/Equipo': typeof AppEquipoRoute
  '/app/Financiero': typeof AppFinancieroRoute
  '/app/Informes': typeof AppInformesRoute
  '/app/Onboarding': typeof AppOnboardingRoute
  '/app/Pacientes': typeof AppPacientesRoute
  '/app/Presupuestos': typeof AppPresupuestosRoute
  '/app/Procedimientos': typeof AppProcedimientosRoute
  '/app/Profesionales': typeof AppProfesionalesRoute
  '/app/Tratamientos': typeof AppTratamientosRoute
  '/demo/Agenda': typeof DemoAgendaRoute
  '/demo/CrecimientoIA': typeof DemoCrecimientoIARoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Financiero': typeof DemoFinancieroRoute
  '/demo/Informes': typeof DemoInformesRoute
  '/demo/Pacientes': typeof DemoPacientesRoute
  '/demo/Presupuestos': typeof DemoPresupuestosRoute
  '/demo/Tratamientos': typeof DemoTratamientosRoute
  '/master/clinicasSuspendidas': typeof MasterClinicasSuspendidasRoute
  '/master/configuracion': typeof MasterConfiguracionRoute
  '/master/listaClinicas': typeof MasterListaClinicasRoute
  '/master/nuevaClinica': typeof MasterNuevaClinicaRoute
  '/master/panel': typeof MasterPanelRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cambiar-contrasena'
    | '/clinica-suspendida'
    | '/demo'
    | '/entrar'
    | '/master'
    | '/olvide-contrasena'
    | '/restablecer-contrasena'
    | '/agendar/$slug'
    | '/app/Agenda'
    | '/app/Configuracion'
    | '/app/CrecimientoIA'
    | '/app/Dashboard'
    | '/app/Equipo'
    | '/app/Financiero'
    | '/app/Informes'
    | '/app/Onboarding'
    | '/app/Pacientes'
    | '/app/Presupuestos'
    | '/app/Procedimientos'
    | '/app/Profesionales'
    | '/app/Tratamientos'
    | '/demo/Agenda'
    | '/demo/CrecimientoIA'
    | '/demo/Dashboard'
    | '/demo/Financiero'
    | '/demo/Informes'
    | '/demo/Pacientes'
    | '/demo/Presupuestos'
    | '/demo/Tratamientos'
    | '/master/clinicasSuspendidas'
    | '/master/configuracion'
    | '/master/listaClinicas'
    | '/master/nuevaClinica'
    | '/master/panel'
    | '/api/public/hotmart-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/cambiar-contrasena'
    | '/clinica-suspendida'
    | '/demo'
    | '/entrar'
    | '/master'
    | '/olvide-contrasena'
    | '/restablecer-contrasena'
    | '/agendar/$slug'
    | '/app/Agenda'
    | '/app/Configuracion'
    | '/app/CrecimientoIA'
    | '/app/Dashboard'
    | '/app/Equipo'
    | '/app/Financiero'
    | '/app/Informes'
    | '/app/Onboarding'
    | '/app/Pacientes'
    | '/app/Presupuestos'
    | '/app/Procedimientos'
    | '/app/Profesionales'
    | '/app/Tratamientos'
    | '/demo/Agenda'
    | '/demo/CrecimientoIA'
    | '/demo/Dashboard'
    | '/demo/Financiero'
    | '/demo/Informes'
    | '/demo/Pacientes'
    | '/demo/Presupuestos'
    | '/demo/Tratamientos'
    | '/master/clinicasSuspendidas'
    | '/master/configuracion'
    | '/master/listaClinicas'
    | '/master/nuevaClinica'
    | '/master/panel'
    | '/api/public/hotmart-webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cambiar-contrasena'
    | '/clinica-suspendida'
    | '/demo'
    | '/entrar'
    | '/master'
    | '/olvide-contrasena'
    | '/restablecer-contrasena'
    | '/agendar/$slug'
    | '/app/Agenda'
    | '/app/Configuracion'
    | '/app/CrecimientoIA'
    | '/app/Dashboard'
    | '/app/Equipo'
    | '/app/Financiero'
    | '/app/Informes'
    | '/app/Onboarding'
    | '/app/Pacientes'
    | '/app/Presupuestos'
    | '/app/Procedimientos'
    | '/app/Profesionales'
    | '/app/Tratamientos'
    | '/demo/Agenda'
    | '/demo/CrecimientoIA'
    | '/demo/Dashboard'
    | '/demo/Financiero'
    | '/demo/Informes'
    | '/demo/Pacientes'
    | '/demo/Presupuestos'
    | '/demo/Tratamientos'
    | '/master/clinicasSuspendidas'
    | '/master/configuracion'
    | '/master/listaClinicas'
    | '/master/nuevaClinica'
    | '/master/panel'
    | '/api/public/hotmart-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CambiarContrasenaRoute: typeof CambiarContrasenaRoute
  ClinicaSuspendidaRoute: typeof ClinicaSuspendidaRoute
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  MasterRoute: typeof MasterRouteWithChildren
  OlvideContrasenaRoute: typeof OlvideContrasenaRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-contrasena': {
      id: '/cambiar-contrasena'
      path: '/cambiar-contrasena'
      fullPath: '/cambiar-contrasena'
      preLoaderRoute: typeof CambiarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica-suspendida': {
      id: '/clinica-suspendida'
      path: '/clinica-suspendida'
      fullPath: '/clinica-suspendida'
      preLoaderRoute: typeof ClinicaSuspendidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olvide-contrasena': {
      id: '/olvide-contrasena'
      path: '/olvide-contrasena'
      fullPath: '/olvide-contrasena'
      preLoaderRoute: typeof OlvideContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/Agenda': {
      id: '/app/Agenda'
      path: '/Agenda'
      fullPath: '/app/Agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Configuracion': {
      id: '/app/Configuracion'
      path: '/Configuracion'
      fullPath: '/app/Configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/CrecimientoIA': {
      id: '/app/CrecimientoIA'
      path: '/CrecimientoIA'
      fullPath: '/app/CrecimientoIA'
      preLoaderRoute: typeof AppCrecimientoIARouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Dashboard': {
      id: '/app/Dashboard'
      path: '/Dashboard'
      fullPath: '/app/Dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Equipo': {
      id: '/app/Equipo'
      path: '/Equipo'
      fullPath: '/app/Equipo'
      preLoaderRoute: typeof AppEquipoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Financiero': {
      id: '/app/Financiero'
      path: '/Financiero'
      fullPath: '/app/Financiero'
      preLoaderRoute: typeof AppFinancieroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Informes': {
      id: '/app/Informes'
      path: '/Informes'
      fullPath: '/app/Informes'
      preLoaderRoute: typeof AppInformesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Onboarding': {
      id: '/app/Onboarding'
      path: '/Onboarding'
      fullPath: '/app/Onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Pacientes': {
      id: '/app/Pacientes'
      path: '/Pacientes'
      fullPath: '/app/Pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Presupuestos': {
      id: '/app/Presupuestos'
      path: '/Presupuestos'
      fullPath: '/app/Presupuestos'
      preLoaderRoute: typeof AppPresupuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Procedimientos': {
      id: '/app/Procedimientos'
      path: '/Procedimientos'
      fullPath: '/app/Procedimientos'
      preLoaderRoute: typeof AppProcedimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Profesionales': {
      id: '/app/Profesionales'
      path: '/Profesionales'
      fullPath: '/app/Profesionales'
      preLoaderRoute: typeof AppProfesionalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Tratamientos': {
      id: '/app/Tratamientos'
      path: '/Tratamientos'
      fullPath: '/app/Tratamientos'
      preLoaderRoute: typeof AppTratamientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/Agenda': {
      id: '/demo/Agenda'
      path: '/Agenda'
      fullPath: '/demo/Agenda'
      preLoaderRoute: typeof DemoAgendaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/CrecimientoIA': {
      id: '/demo/CrecimientoIA'
      path: '/CrecimientoIA'
      fullPath: '/demo/CrecimientoIA'
      preLoaderRoute: typeof DemoCrecimientoIARouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Dashboard': {
      id: '/demo/Dashboard'
      path: '/Dashboard'
      fullPath: '/demo/Dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Financiero': {
      id: '/demo/Financiero'
      path: '/Financiero'
      fullPath: '/demo/Financiero'
      preLoaderRoute: typeof DemoFinancieroRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Informes': {
      id: '/demo/Informes'
      path: '/Informes'
      fullPath: '/demo/Informes'
      preLoaderRoute: typeof DemoInformesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Pacientes': {
      id: '/demo/Pacientes'
      path: '/Pacientes'
      fullPath: '/demo/Pacientes'
      preLoaderRoute: typeof DemoPacientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Presupuestos': {
      id: '/demo/Presupuestos'
      path: '/Presupuestos'
      fullPath: '/demo/Presupuestos'
      preLoaderRoute: typeof DemoPresupuestosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Tratamientos': {
      id: '/demo/Tratamientos'
      path: '/Tratamientos'
      fullPath: '/demo/Tratamientos'
      preLoaderRoute: typeof DemoTratamientosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/master/clinicasSuspendidas': {
      id: '/master/clinicasSuspendidas'
      path: '/clinicasSuspendidas'
      fullPath: '/master/clinicasSuspendidas'
      preLoaderRoute: typeof MasterClinicasSuspendidasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracion': {
      id: '/master/configuracion'
      path: '/configuracion'
      fullPath: '/master/configuracion'
      preLoaderRoute: typeof MasterConfiguracionRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/listaClinicas': {
      id: '/master/listaClinicas'
      path: '/listaClinicas'
      fullPath: '/master/listaClinicas'
      preLoaderRoute: typeof MasterListaClinicasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/nuevaClinica': {
      id: '/master/nuevaClinica'
      path: '/nuevaClinica'
      fullPath: '/master/nuevaClinica'
      preLoaderRoute: typeof MasterNuevaClinicaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/panel': {
      id: '/master/panel'
      path: '/panel'
      fullPath: '/master/panel'
      preLoaderRoute: typeof MasterPanelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/api/public/hotmart-webhook': {
      id: '/api/public/hotmart-webhook'
      path: '/api/public/hotmart-webhook'
      fullPath: '/api/public/hotmart-webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppCrecimientoIARoute: typeof AppCrecimientoIARoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipoRoute: typeof AppEquipoRoute
  AppFinancieroRoute: typeof AppFinancieroRoute
  AppInformesRoute: typeof AppInformesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppPresupuestosRoute: typeof AppPresupuestosRoute
  AppProcedimientosRoute: typeof AppProcedimientosRoute
  AppProfesionalesRoute: typeof AppProfesionalesRoute
  AppTratamientosRoute: typeof AppTratamientosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppCrecimientoIARoute: AppCrecimientoIARoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipoRoute: AppEquipoRoute,
  AppFinancieroRoute: AppFinancieroRoute,
  AppInformesRoute: AppInformesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppPresupuestosRoute: AppPresupuestosRoute,
  AppProcedimientosRoute: AppProcedimientosRoute,
  AppProfesionalesRoute: AppProfesionalesRoute,
  AppTratamientosRoute: AppTratamientosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAgendaRoute: typeof DemoAgendaRoute
  DemoCrecimientoIARoute: typeof DemoCrecimientoIARoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoFinancieroRoute: typeof DemoFinancieroRoute
  DemoInformesRoute: typeof DemoInformesRoute
  DemoPacientesRoute: typeof DemoPacientesRoute
  DemoPresupuestosRoute: typeof DemoPresupuestosRoute
  DemoTratamientosRoute: typeof DemoTratamientosRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAgendaRoute: DemoAgendaRoute,
  DemoCrecimientoIARoute: DemoCrecimientoIARoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoFinancieroRoute: DemoFinancieroRoute,
  DemoInformesRoute: DemoInformesRoute,
  DemoPacientesRoute: DemoPacientesRoute,
  DemoPresupuestosRoute: DemoPresupuestosRoute,
  DemoTratamientosRoute: DemoTratamientosRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterClinicasSuspendidasRoute: typeof MasterClinicasSuspendidasRoute
  MasterConfiguracionRoute: typeof MasterConfiguracionRoute
  MasterListaClinicasRoute: typeof MasterListaClinicasRoute
  MasterNuevaClinicaRoute: typeof MasterNuevaClinicaRoute
  MasterPanelRoute: typeof MasterPanelRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterClinicasSuspendidasRoute: MasterClinicasSuspendidasRoute,
  MasterConfiguracionRoute: MasterConfiguracionRoute,
  MasterListaClinicasRoute: MasterListaClinicasRoute,
  MasterNuevaClinicaRoute: MasterNuevaClinicaRoute,
  MasterPanelRoute: MasterPanelRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CambiarContrasenaRoute: CambiarContrasenaRoute,
  ClinicaSuspendidaRoute: ClinicaSuspendidaRoute,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  MasterRoute: MasterRouteWithChildren,
  OlvideContrasenaRoute: OlvideContrasenaRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
